---
include:
  - board: sofle_dongle
    shield: st7789_display
  - board: sofle_dongle_left
    shield: lpm_view;left_bbtrackball_dongle
  - board: sofle_dongle_right
    shield: lpm_view;right_trackpoint_dongle


  - board: sofle_dongle
    shield: st7789_display;settings_reset
  - board: sofle_dongle_left
    shield: lpm_view;left_bbtrackball_dongle;settings_reset
  - board: sofle_dongle_right
    shield: lpm_view;right_trackpoint_dongle;settings_reset
